source 'https://rubygems.org'
gem 'rails', '4.1.6'
gem 'pg'
gem 'uglifier', '>= 1.3.0'

gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development
gem 'rspec'
